# File: .github/workflows/repo-sync.yml    建立一个分支，把此文件放进分支的AC里
name: sync-momo
on:
  schedule:
    - cron: '1 20 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-momo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync momo
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/gonfei/momo-share.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
